stages:
    - test
    - deploy

cache:
  paths:
    - node_modules/
    - ${HOME}/.yarn-cache
    - ${HOME}/.npm

.common: &common
  except:
    - tags
  stage: test

.node_0_10: &node_0_10
  image: node:0.10

.node_0_12: &node_0_12
  image: node:0.12

.node_4: &node_4
  image: node:4

.node_6: &node_6
  image: node:6

.yarn: &yarn
  after_script:
    - $(yarn bin)/codecov
  script:
    - yarn && yarn test

.yarn_0_15: &yarn_0_15
  <<: [*yarn]
  before_script:
    - npm install --global yarn@0.15

.npm: &npm
  after_script:
    - npm update && npm test && $(npm bin)/codecov
  before_script:
    - npm prune

.npm_2: &npm_2
  <<: [*npm]
  script:
    - npm install --global npm@2

.npm_3: &npm_3
  <<: [*npm]
  script:
    - npm install --global npm@3

node_0_10_npme_2:
  <<: [*common, *node_0_10, *npm_2]

node_0_10_npm_3:
  <<: [*common, *node_0_10, *npm_3]

node_0_12_npme_2:
  <<: [*common, *node_0_12, *npm_2]

node_0_12_npm_3:
  <<: [*common, *node_0_12, *npm_3]

node_4_npm_2:
  <<: [*common, *node_4, *npm_2]

node_4_npm_3:
  <<: [*common, *node_4, *npm_3]

node_4_yarn_0_15:
  <<: [*common, *node_4, *yarn_0_15]

node_6_npm_2:
  <<: [*common, *node_6, *npm_2]
  allow_failure: true

node_6_npm_3:
  <<: [*common, *node_6, *npm_3]
  allow_failure: true

node_6_yarn_0_15:
  <<: [*common, *node_6, *yarn_0_15]

publish:
  <<: [*node_6]
  before_script:
    - npm install semantic-release-gitlab
  only:
    - master@hutson/winston-gulplog
  script:
    - $(npm bin)/semantic-release-gitlab
  stage: deploy
