stages:
    - test
    - deploy

cache:
  paths:
    - node_modules/
    - ${HOME}/.yarn-cache
    - ${HOME}/.npm

.common: &common
  except:
    - tags
  stage: test

.node_0_12: &node_0_12
  image: node:0.12

.node_4: &node_4
  image: node:4

.node_6: &node_6
  image: node:6

.node_next: &node_next
  image: node:latest

.yarn: &yarn
  after_script:
    - yarn && yarn test && $(yarn bin)/codecov

.npm: &npm
  after_script:
    - npm update && npm test && $(npm bin)/codecov
  before_script:
    - npm prune

.yarn_0_16: &yarn_0_16
  <<: [*yarn]
  script:
    - npm install --global yarn@0.16

.npm_2: &npm_2
  <<: [*npm]
  script:
    - npm install --global npm@2

.npm_3: &npm_3
  <<: [*npm]
  script:
    - npm install --global npm@3

.npm_4: &npm_4
  <<: [*npm]
  script:
    - npm install --global npm@4

.npm_next: &npm_next
  <<: [*npm]
  script:
    - npm install --global npm@next

node_0_12_npme_2:
  <<: [*common, *node_0_12, *npm_2]

node_0_12_npm_3:
  <<: [*common, *node_0_12, *npm_3]

node_0_12_npm_4:
  <<: [*common, *node_0_12, *npm_4]

node_0_12_npm_next:
  <<: [*common, *node_0_12, *npm_next]
  allow_failure: true

node_4_npm_2:
  <<: [*common, *node_4, *npm_2]

node_4_npm_3:
  <<: [*common, *node_4, *npm_3]

node_4_npm_4:
  <<: [*common, *node_4, *npm_4]

node_4_npm_next:
  <<: [*common, *node_4, *npm_next]
  allow_failure: true

node_4_yarn_0_16:
  <<: [*common, *node_4, *yarn_0_16]

node_6_npm_2:
  <<: [*common, *node_6, *npm_2]
  allow_failure: true

node_6_npm_3:
  <<: [*common, *node_6, *npm_3]
  allow_failure: true

node_6_npm_4:
  <<: [*common, *node_6, *npm_4]
  allow_failure: true

node_6_npm_next:
  <<: [*common, *node_6, *npm_next]
  allow_failure: true

node_6_yarn_0_16:
  <<: [*common, *node_6, *yarn_0_16]
  allow_failure: true

node_next_npm_2:
  <<: [*common, *node_next, *npm_2]
  allow_failure: true

node_next_npm_3:
  <<: [*common, *node_next, *npm_3]
  allow_failure: true

node_next_npm_4:
  <<: [*common, *node_next, *npm_4]
  allow_failure: true

node_next_npm_next:
  <<: [*common, *node_next, *npm_next]
  allow_failure: true

node_next_yarn_0_16:
  <<: [*common, *node_next, *yarn_0_16]
  allow_failure: true

publish:
  <<: [*node_6]
  before_script:
    - npm install --production
  only:
    - master@hyper-expanse/semantic-release-gitlab
  script:
    - node ./src/cli.js
  stage: deploy
