image: node:4

stages:
    - test
    - deploy

cache:
  paths:
    - node_modules/

.all_jobs: &all_jobs_definition
  after_script:
    - $(npm bin)/codecov
  script:
    - $(npm bin)/npm install
    - $(npm bin)/npm test

.node_010: &node_010_definition
  <<: *all_jobs_definition
  image: node:0.10

.node_012: &node_012_definition
  <<: *all_jobs_definition
  image: node:0.12

.node_4: &node_4_definition
  <<: *all_jobs_definition
  image: node:4

npm_2_node_010:
  <<: *node_010_definition
  before_script:
    - npm install npm@2
  stage: test

npm_3_node_010:
  <<: *node_010_definition
  before_script:
    - npm install npm@3
  stage: test

npm_2_node_012:
  <<: *node_012_definition
  before_script:
    - npm install npm@2
  stage: test

npm_3_node_012:
  <<: *node_012_definition
  before_script:
    - npm install npm@3
  stage: test

npm_2_node_4:
  <<: *node_4_definition
  before_script:
    - npm install npm@2
  stage: test

npm_3_node_4:
  <<: *node_4_definition
  before_script:
    - npm install npm@3
  stage: test

publish:
  before_script:
    - npm install semantic-release-gitlab
  only:
    - master@hutson/semantic-release-gitlab
  script:
    - echo "publish"
  stage: deploy
